### ISSUE TITLE
Error while running action

### ISSUE THREAD

**Issue by envoy1084** [noir-lang/noir-gates-diff#16]
### Aim

I am getting this error while running the workflow action

```
/home/runner/.bb/bb: error while loading shared libraries: libc++.so.1: cannot open shared object file: No such file or directory
```

Here is my workflow file

```yaml
name: Benchmarks

on:
  push:
   branches:
    - main
  pull_request:

jobs:
  test:
    name: Benchmark library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Nargo
        uses: noir-lang/noirup@v0.1.3
        with:
          toolchain: 0.36.0

      - name: Install bb
        run: |
          npm install -g bbup
          bbup -nv 0.36.0
      - name: Build Noir benchmark programs
        run: nargo export

      - name: Generate gates report
        run: ./scripts/build-gates-report.sh
        env:
          BACKEND: /home/runner/.bb/bb

      - name: Compare gates reports
        id: gates_diff
        uses: noir-lang/noir-gates-diff@dbe920a8dcc3370af4be4f702ca9cef29317bec1
        with:
          report: gates_report.json
          summaryQuantile: 0.9 # only display the 10% most significant circuit size diffs in the summary (defaults to 20%)

      - name: Add gates diff to sticky comment
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          # delete the comment in case changes no longer impact circuit sizes
          delete: ${{ !steps.gates_diff.outputs.markdown }}
          message: ${{ steps.gates_diff.outputs.markdown }}

```

### Expected Behavior

Should Generate Gates Diff

### Bug

```
/home/runner/.bb/bb: error while loading shared libraries: libc++.so.1: cannot open shared object file: No such file or directory
```

### To Reproduce

1. Use workflow file specified in description
2. Push code to trigger workflow run

### Workaround

None

### Project Impact

None

### Would you like to submit a PR for this Issue?

None
